### ISSUE TITLE
建议将编译安装时的 CGO 改成默认禁用

### ISSUE THREAD

**Issue by chika0801** [KoinuDayo/sing-box-Install#12]
它官方github生成的是CGO禁用了的。

我当时用时，好像是看到 https://sing-box.sagernet.org/zh/configuration/dns/server/#address 这里的这句

`为了确保系统 DNS 生效，而不是 Go 的内置默认解析器，请在编译时启用 CGO。`

就把CGO启用了，虽然我也不太懂效果差异。和上面这句话到底怎么验证效果之类。

我觉得还是遵从官方的禁用CGO好了。

**Comment by KoinuDayo** [comment]
https://github.com/KoinuDayo/sing-box-Install/commit/821336d6b05576ae246841dbca9c0f455835ac27 改了，现在使用 `--cgo` 使用 `CGO_ENABLED`

**Comment by chika0801** [comment]
没想到提的事，这个意外解决这个困扰我的莫名现象

https://github.com/SagerNet/sing-box/issues/712

**Comment by KoinuDayo** [comment]
> 没想到这个能意外解决这个困扰我的莫名现象
> 
> [SagerNet/sing-box#712](https://github.com/SagerNet/sing-box/issues/712)

~~恭喜解决！~~
