### ISSUE TITLE
安装时缺少sing-box.fish

### ISSUE THREAD

**Issue by Morris-Lucifer** [KoinuDayo/sing-box-Install#17]
chise佬，安装时报错
```
bash -c "$(curl -L sing-box.vercel.app)" @ install --user=root
install: cannot create regular file '/usr/share/fish/vendor_completions.d/sing-box.fish': No such file or directory
ERROR: Failed to Install "/usr/share/fish/vendor_completions.d/sing-box.fish"
```
但是查询sing-box进程状态正常运行，会有影响吗？（还没配客户端

系统：Debian 12

**Comment by Morris-Lucifer** [comment]
客户端配好了，但是又遇到了上次[同样的问题](https://github.com/chise0713/sing-box-install/issues/13#issuecomment-1826807583) TAT

**Comment by chise0713** [comment]
读取之前的配置和 fish 的自动补全安装失败都是我脚本的问题，没在卸载时把 `/etc/systemd/system/sing-box.service.d` 和 `/etc/systemd/system/sing-box@.service.d` 一起删除，安装 fish 自动补全没自动创建文件夹。
然后其实不推荐用我这个脚本了，https://sing-box.sagernet.org/installation/package-manager/ 这里有包管理安装和脚本安装的方法。
https://t.me/yaeug 关于 sing-box 的问题可以加这个群组讨论。

**Comment by Morris-Lucifer** [comment]
不知道是不是因为beta版已经合并到正式版里了，包管理安装和chika佬的手动下载安装都不能解决hy2连不上的问题，感觉有可能是因为我客户端是nekoray不是纯json配置的所以字段有点问题吧。。群组提问总感觉有点社恐，等我实在解决不了了再问吧hh

**Comment by Morris-Lucifer** [comment]
解决了hy2连不上原来是服务器防火墙没设置（菜）
