### ISSUE TITLE
README 里面仿照 Xray-install 的样式建议

### ISSUE THREAD

**Issue by chika0801** [KoinuDayo/sing-box-Install#2]
```
installed: /etc/systemd/system/sing-box.service
installed: /etc/systemd/system/sing-box@.service

installed: /usr/local/bin/sing-box
Installed: /usr/local/etc/sing-box/*.json

Installed: /usr/local/etc/sing-box/geoip.db
Installed: /usr/local/etc/sing-box/geosite.db

installed: /var/log/sing-box/sing.log
```

**Comment by chika0801** [comment]
geoip.db geosite.db 看了下，所以应该会默认下载到 `/usr/local/etc/sing-box/`

`WorkingDirectory=/usr/local/etc/sing-box/`

**Comment by KoinuDayo** [comment]
https://github.com/KoinuDayo/sing-box-Install/commit/30bdad351ed691ce249ba7abc514c4dc36a5e0fa
顺便为了遵循FHS标准把工作目录换成 `/usr/local/share/sing-box/` 了

**Comment by KoinuDayo** [comment]
https://github.com/KoinuDayo/sing-box-Install/commit/b6842106ac072212b26e5eb18b6dbfa9ea54402a
顺便为了遵循FHS标准，把工作文件夹换成 `/usr/local/share/sing-box` 了

**Comment by chika0801** [comment]
```
    "log": {
        "output": "box.log",
        "level": "info",
        "timestamp": true
    },

```

` "output": "box.log",` 它这个参数，如果自己不写位置，我测试了下生成的box.log文件的目录是 `WorkingDirectory=/usr/local/share/sing-box`

不要你在README中把 `Installed: /var/log/sing-box/sing.log` 改成 `/usr/local/share/sing-box` 虽然这规范不是强制性要求的。

**Comment by KoinuDayo** [comment]
> 不要你在README中把 `Installed: /var/log/sing-box/sing.log` 改成 `/usr/local/share/sing-box` 虽然这规范不是强制性要求的。

想了想，我把这段安装log文件的删了，我认为systemd自带的journalctl是更好的日志存储方法
