### ISSUE TITLE
Debian 12 使用一键脚本编译失败

### ISSUE THREAD

**Issue by chika0801** [KoinuDayo/sing-box-Install#3]
```
root@localhost:~# bash -c "$(curl -L https://github.com/KoinuDayo/Sing-box-Install/raw/master/install.sh)" -- install --go

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 10967  100 10967    0     0   115k      0 --:--:-- --:--:-- --:--:--  115k

error: Installation of go failed, please check your network.
```

日志如上

**Comment by chika0801** [comment]
```
curl -sLo go.tar.gz https://go.dev/dl/go1.21.0.linux-amd64.tar.gz
rm -rf /usr/local/go
tar -C /usr/local -xzf go.tar.gz
rm go.tar.gz
echo -e "export PATH=$PATH:/usr/local/go/bin" > /etc/profile.d/go.sh
source /etc/profile.d/go.sh
go version
```

解决了，原来是要自己准备 go 。

**Comment by chika0801** [comment]
要不你写在README里提醒一下。或者有空把下载go加到脚本中。

**Comment by KoinuDayo** [comment]
https://github.com/KoinuDayo/Sing-box-Install/blob/master/install.sh#L202-L214
脚本内是有在go安装失败后尝试官方脚本的内容，似乎没能成功用上，我看看是哪里出问题了

**Comment by KoinuDayo** [comment]
https://github.com/KoinuDayo/sing-box-Install/commit/30bdad351ed691ce249ba7abc514c4dc36a5e0fa
似乎是因为函数 `exit 1` 时直接退出了，我换成直接用脚本安装而不是包管理安装，现在应该没问题了，可以试试看还会不会出错。

**Comment by KoinuDayo** [comment]
https://github.com/KoinuDayo/sing-box-Install/commit/b6842106ac072212b26e5eb18b6dbfa9ea54402a
似乎是因为函数 exit 1 时直接退出了，我换成直接用脚本安装而不是包管理安装，现在应该没问题了，可以试试看还会不会出错。

**Comment by chika0801** [comment]
测试了下 卡在这儿了。
```
github.com/sagernet/wireguard-go/ratelimiter
github.com/sagernet/wireguard-go/replay
github.com/sagernet/wireguard-go/tai64n
golang.org/x/crypto/blake2s
golang.org/x/crypto/poly1305
golang.org/x/crypto/blowfish
golang.org/x/crypto/ssh/internal/bcrypt_pbkdf
github.com/sagernet/sing-box/common/sniff/internal/qtls
github.com/sagernet/sing/common/domain
html
internal/lazyregexp
internal/profile
text/tabwriter
runtime/pprof
runtime/trace
encoding/csv
text/template/parse
text/template
os/signal
Go Install Failed.
Exiting.
root@localhost:~# 

```

**Comment by chika0801** [comment]
```
# Parse command line arguments
for arg in "$@"; do
  case $arg in
    --purge)
      remove_type="purge"
      ;;
    --go)
      type="go"
      ;;
    --tag=*)
      tag="${arg#*=}"
      go_type=custom
      type=go
      ;;
    help)
      action="help"
      ;;
    remove)
      action="remove"
      ;;
    install)
      action="install"
      ;;
    *)
      echo "Invalid argument: $arg"
      exit 1
      ;;
  esac
done

# Perform action based on user input
case "$action" in
  help)
    help
    ;;
  remove)
    uninstall
    ;;
  install)
    curl_install
    ;;
  *)
    echo "No action specified. Exiting..."
    ;;
esac

helpINFO: Installing go
go version go1.21.0 linux/amd64
INFO: go installed PATH: /usr/local/go/bin/go
Use @chika0801's template by default.
runtime/cgo
# runtime/cgo
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH
Go Install Failed.
Exiting.
root@localhost:~# 

```


问AI 用 `curl -L https://github.com/KoinuDayo/sing-box-Install/raw/master/install.sh | tee /dev/tty | bash -s -- install --go
`
内容为上面的。

**Comment by KoinuDayo** [comment]
看了下，你试试看先 `apt install gcc` ？cgo有要求自己先安装编译器，如果是因为这个的话我脚本内再加个自动安装gcc的

**Comment by KoinuDayo** [comment]
https://github.com/KoinuDayo/sing-box-Install/commit/71b3196772c5a943fb9ab1e7eb83b0e04f94cc25 里已经加上在编译前安装 `gcc` 了，现在可以再试试看吗？

**Comment by chika0801** [comment]
```
# Parse command line arguments
for arg in "$@"; do
  case $arg in
    --purge)
      remove_type="purge"
      ;;
    --go)
      type="go"
      ;;
    --tag=*)
      tag="${arg#*=}"
      go_type=custom
      type=go
      ;;
    help)
      action="help"
      ;;
    remove)
      action="remove"
      ;;
    install)
      action="install"
      ;;
    *)
      echo "Invalid argument: $arg"
      exit 1
      ;;
  esac
done

# Perform action based on user input
case "$action" in
  help)
    help
    ;;
  remove)
    uninstall
    ;;
  install)
    main
    ;;
  *)
    echo "No action specified. Exiting..."
    ;;
esac

helpmain: line 127: Error:: command not found
INFO: Installing go
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    75  100    75    0     0    376      0 --:--:-- --:--:-- --:--:--   378
100 63.3M  100 63.3M    0     0  76.0M      0 --:--:-- --:--:-- --:--:--  110M
go version go1.21.0 linux/amd64
INFO: go installed PATH: /usr/local/go/bin/go
Use @chika0801's template by default.
runtime/cgo
# runtime/cgo
_cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
    3 | #include <stdlib.h>
      |          ^~~~~~~~~~
compilation terminated.
Go Install Failed.
Exiting.

```

重新安装的debian 12，失败在这儿。

**Comment by KoinuDayo** [comment]
我的锅，似乎是没有下载标准库，我待会把自动安装gcc换成自动安装编译环境的包
~~还得根据不同发行版的不同包管理系统判断该安装哪个包，头开始大了~~

**Comment by chika0801** [comment]
> 我的锅，似乎是没有下载标准库，我待会把自动安装gcc换成自动安装编译环境的包 ~还得根据不同发行版的不同包管理系统判断该安装哪个包，头开始大了~

建议不要加这功能，立省100%

**Comment by KoinuDayo** [comment]
现在就先这样了，我找时间再做
要想一键编译的话就先用包管理安装build-essential（debian系）base-devel（arch系/void linux）Development Tools（CentOS/Fedora）build-base（alpine linux）system.devel（Solus）

**Comment by chika0801** [comment]
> 现在就先这样了，我找时间再做 要想一键编译的话就先用包管理安装build-essential（debian系）base-devel（arch系/void linux）Development Tools（CentOS/Fedora）build-base（alpine linux）system.devel（Solus）

你在README上写上这段，就不用改脚本了，也可以省事，好多

**Comment by KoinuDayo** [comment]
> > 现在就先这样了，我找时间再做 要想一键编译的话就先用包管理安装build-essential（debian系）base-devel（arch系/void linux）Development Tools（CentOS/Fedora）build-base（alpine linux）system.devel（Solus）
> 
> 你在README上写上这段，就不用改脚本了，也可以省事，好多，懂的自然懂，不懂的也不需要懂的道理。

我实际上是想做到让我的脚本真的一键全部完成，反正也没什么事做，就折腾下吧🤪

**Comment by chika0801** [comment]
> > > 现在就先这样了，我找时间再做 要想一键编译的话就先用包管理安装build-essential（debian系）base-devel（arch系/void linux）Development Tools（CentOS/Fedora）build-base（alpine linux）system.devel（Solus）
> > 
> > 
> > 你在README上写上这段，就不用改脚本了，也可以省事，好多，懂的自然懂，不懂的也不需要懂的道理。
> 
> 我实际上是想做到让我的脚本真的一键全部完成，反正也没什么事做，就折腾下吧🤪

没事做不如去现充呀

**Comment by KoinuDayo** [comment]
> > > > 现在就先这样了，我找时间再做 要想一键编译的话就先用包管理安装build-essential（debian系）base-devel（arch系/void linux）Development Tools（CentOS/Fedora）build-base（alpine linux）system.devel（Solus）
> > > 
> > > 
> > > 你在README上写上这段，就不用改脚本了，也可以省事，好多，懂的自然懂，不懂的也不需要懂的道理。
> > 
> > 
> > 我实际上是想做到让我的脚本真的一键全部完成，反正也没什么事做，就折腾下吧🤪
> 
> 没事做不如去现充呀

现实生活好可怕呜呜┭┮﹏┭┮

**Comment by KoinuDayo** [comment]
https://github.com/KoinuDayo/sing-box-Install/blob/6c0e952134ac2b5dc7496c7e75130c48325ddfa8/install.sh#L209-L239
完成了，现在会在编译之前检测是否安装了构建部件，没安装的话会自动安装

**Comment by chika0801** [comment]
测试了debian10-12 都正常编译成功了。
