### ISSUE TITLE
建议脚本中生成的 sing-box.service 内容使用 sing-box 官方的

### ISSUE THREAD

**Issue by chika0801** [KoinuDayo/sing-box-Install#4]
https://github.com/SagerNet/sing-box/blob/dev-next/release/config/sing-box.service

https://github.com/SagerNet/sing-box/blob/dev-next/release/config/sing-box%40.service

它有官方的就用它的更好。

**Comment by chika0801** [comment]
```
[Unit]
Description=sing-box service
Documentation=https://sing-box.sagernet.org
After=network.target nss-lookup.target
```

```
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_SYS_PTRACE CAP_DAC_READ_SEARCH
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_SYS_PTRACE CAP_DAC_READ_SEARCH
```

这几项吧，其它也没什么了。

**Comment by KoinuDayo** [comment]
https://github.com/KoinuDayo/sing-box-Install/commit/eaa3e3ebfd8c02c15ae12922f7b9ff23f7c7abd6
