### ISSUE TITLE
建议使用 -- install --go 安装时的 tag 与 sing-box 官方的一致。

### ISSUE THREAD

**Issue by chika0801** [KoinuDayo/sing-box-Install#5]
现在默认编译好后的tag是
```
Tags: with_wireguard,with_quic,with_utls,with_reality_server
```

我下载了官方 1.4.0-rc.3 是

```
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_utls,with_reality_server,with_clash_api
```

**Comment by chika0801** [comment]
| Feature           | Set 1                                      | Set 2                                        |
|-------------------|--------------------------------------------|----------------------------------------------|
| WireGuard         | with_wireguard                             | with_wireguard                              |
| QUIC              | with_quic                                  | with_quic                                   |
| uTLS              | with_utls                                  | with_utls                                   |
| Reality Server    | with_reality_server                        | with_reality_server                         |
| gVisor            | N/A (not mentioned in Set 1)              | with_gvisor                                 |
| DHCP              | N/A (not mentioned in Set 1)              | with_dhcp                                   |
| Clash API         | N/A (not mentioned in Set 1)              | with_clash_api                              |


问GPT生成的真方便

**Comment by KoinuDayo** [comment]
https://github.com/KoinuDayo/sing-box-Install/commit/3564a3de163031bd6fef6bd330221eebe49d42f5

**Comment by chika0801** [comment]
https://github.com/SagerNet/sing-box/commit/49601a590b6b2b055dfa3ef366bb88a3cf3c1816

它今天新增加了这个默认tag

**Comment by KoinuDayo** [comment]
Sync: https://github.com/KoinuDayo/sing-box-Install/commit/63ff5a300c0c0e5aecaf5837eb684e8c95833cd6

> [SagerNet/sing-box@49601a5](https://github.com/SagerNet/sing-box/commit/49601a590b6b2b055dfa3ef366bb88a3cf3c1816)
> 
> 它今天新增加了这个默认tag
