### ISSUE TITLE
建议新加 --beta 下载官方最新的版本

### ISSUE THREAD

**Issue by chika0801** [KoinuDayo/sing-box-Install#6]
使其能下载 Pre-release 的版本文件

**Comment by chika0801** [comment]
PS `chika0801's template by default`

希望把脚本中，上面的输出给删了，我也是抄的群里最早谁发的教程编译方法的指南，不然我也不知道编译从何下手，慢慢学才有的套路模板。不是原创。

**Comment by KoinuDayo** [comment]
https://github.com/KoinuDayo/sing-box-Install/commit/8ecf732532b03324816406fd0b5d0a4c4ac01b26

**Comment by KoinuDayo** [comment]
> PS `chika0801's template by default`
> 
> 希望把脚本中，上面的输出给删了。
> 
> 我最早也是看见群里谁发的Xray编译方法的指南，不然我也不知道编译从何下手。日后就慢慢学，才有的套路模板。不是原创。

https://github.com/KoinuDayo/sing-box-Install/commit/3564a3de163031bd6fef6bd330221eebe49d42f5

**Comment by chika0801** [comment]
`Thanks @chika0801.`

希望把运行成这句提示去了。太羞人了。

**Comment by KoinuDayo** [comment]
Removed: https://github.com/KoinuDayo/sing-box-Install/commit/9f22af3de28facf56991409a1d1008873c8beb12
