### ISSUE TITLE
建议为 github.com/KoinuDayo/Sing-box-Install 申请个短链，美观一些

### ISSUE THREAD

**Issue by chika0801** [KoinuDayo/sing-box-Install#9]
如题。可考虑下。

**Comment by KoinuDayo** [comment]
这个没想到过，具体是怎么做？

**Comment by chika0801** [comment]
我也没去了解过github官方短链怎么申请，印象中在哪看到好像现在不能了？

**Comment by ahdiua** [comment]
很难不支持。短链很适合我这种懒癌

**Comment by KoinuDayo** [comment]
[git.io](https://git.io/) 找到了个但是已经不提供服务了

**Comment by chika0801** [comment]
https://github.com/i-abc/GB5

我看这个作者是自己买的.top域名，你也搞个？

**Comment by KoinuDayo** [comment]
> https://github.com/i-abc/GB5
> 
> 我看这个作者是自己买的.top域名，你也搞个？
> 
> bash <(curl -sL gb5.top)
> 
> 像这种买个短的，挺酷

~~买不太起，eu.org我也注册不了~~
